### ISSUE TITLE
Offer downloads for both 1.12 and 1.13 versions

### ISSUE THREAD

**Issue by eminence** [overviewer/Overviewer-Web#14]
Once https://github.com/overviewer/Minecraft-Overviewer/pull/1471 is merged, I think we'll want to offer downloads for both versions of overviewer -- one version for 1.12 and older, and another version for 1.13 and newer.

CC @agrif

**Comment by CounterPillow** [comment]
This can probably be closed since 1.12 maps work fine in the current master

**Comment by eminence** [comment]
:+1:

**Comment by CounterPillow** [comment]
:kissing_heart:
