### ISSUE TITLE
/example/ needs fixing

### ISSUE THREAD

**Issue by CounterPillow** [overviewer/Overviewer-Web#36]
The updated buildbot stuff broke https://overviewer.org/example/ which now needs to be fixed. AFAIK @agrif mentioned this was due to some weirdness with how buildbot dealt with the result of the render job.

**Comment by pironic** [comment]
let me know if you guys need resources from me for this...

**Comment by CounterPillow** [comment]
Will be fixed by #41

**Comment by agrif** [comment]
The problem that caused this was obscured by my awful buildbot-generator-thing, which ate *all* TypeErrors generated inside a build. This is fixed now: 492548a7dfff81d695acab980532edf6a55e032b
